# Welcome new users by commenting on the first-time issue/PR.
# Adding a friendly message in the comment to tip non-stargazers to star our repo.
#
# Props to https://github.com/wow-actions/welcome

name: Welcome New Users with Thanks ;-)
on:
  pull_request_target:
    types: [opened, closed]
  issues:
    types: [opened]
permissions:
  contents: read  # Set permissions as read-only by default at the top level
jobs:
  run:
    permissions:
      issues: write  # for wow-actions/welcome to comment on issues
      pull-requests: write  # wow-actions/welcome to comment on PRs
    # Do not run on bots and maintainers
    if: ${{ !contains(fromJson('["dependabot[bot]", "dependabot-preview[bot]", "allcontributors[bot]"]'), github.actor) }}
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/welcome@68019c2c271561f63162fea75bb7707ef8a02c85 # To pin v1.3.1
        with:
          # GitHub token as default GITHUB_TOKEN

          FIRST_ISSUE_REACTIONS: '+1, hooray, rocket, heart'

          FIRST_ISSUE: |
            ğŸ‘‹ @{{ author }}

            Welcome to the OSS first contribution community! ğŸ’–

            Thanks and congrats ğŸ‰ for opening your first issue here! Be sure to follow the issue template or please update it accordingly.
            Hope you have a great time there!

          FIRST_PR_REACTIONS: '+1, hooray, rocket, heart'

          FIRST_PR: |
            ğŸ‘‹ @{{ author }}

            Welcome to the OSS first contribution community! ğŸ’–

            Thanks and congrats ğŸ‰ for opening your first pull request here! Be sure to follow the pull request template or please update it accordingly.

            Kindly help give the project a star ğŸŒŸ

            Hope you have a great time there!

          FIRST_PR_MERGED: |
            ğŸ‰ @{{ author }}

            You are now an OSS first contribution community contributor! ğŸ’–

            Thanks and congrats ğŸš€ on merging your first pull request! We are delighted and very proud of you! ğŸ‘

            Kudos and please keep going, we need you ğŸ™Œ

          STAR_MESSAGE: |
            ğŸŒŸ ~~~~~~~~~ ğŸŒŸ

            ğŸ“¢ Please â­ star â­ our repo to support it!

            ğŸ™ It really helps the project to gain momentum and credibility. It's a small contribution back to the project with a big impact.

